---
### this task file need to be call with the binary whanted to install in the variable _vmu_bin
### the variable _vmu_bin is can be insert, storage or select
- name: "Set facs user & group for {{ _vmu_bin }}"
  ansible.builtin.set_fact:
    _vmu_system_user: "{{ vars['victoriametrics_' + _vmu_bin + '_system_user'] }}"
    _vmu_system_group: "{{ vars['victoriametrics_' + _vmu_bin + '_system_group'] }}"

- name: "Push relabel config for vminsert"
  ansible.builtin.template:
    src: "relabel.yml.j2"
    dest: "{{ _victoriametrics_config_dir }}/relabel.yml"
    mode: "0644"
    owner: "{{ _vmu_system_user }}"
    group: "{{ _vmu_system_group }}"
  notify: "Restart vm{{ _vmu_bin }}"
  when: _vmu_bin == "insert"

- name: "Push service file for vm{{ _vmu_bin }}"
  ansible.builtin.template:
    src: "vmbinary.service.j2"
    dest: "/etc/systemd/system/vm{{ _vmu_bin }}.service"
    mode: "0644"
  notify: "Reload systemd"
