---
### this task file need to be call with the binary whanted to install in the variable _vmu_bin
- name: "Set bin path"
  ansible.builtin.set_fact:
    _vmu_full_bin_path: "{{ _victoriametrics_binary_install_dir }}/vm{{ _vmu_bin }}-prod"

- name: "Check presnece of {{ _vmu_bin }}"
  ansible.builtin.stat:
    path: "{{ _vmu_full_bin_path }}"
  register: bin_installed

- name: "Get installed version of {{ _vmu_bin }}"
  ansible.builtin.shell: "{{ _vmu_full_bin_path }} --version | grep -oP 'v\\d+\\.\\d+\\.\\d+'"
  register: bin_installed_version
  changed_when: false
  failed_when: false
  ignore_errors: true
  when: bin_installed.stat.exists

- name: "Install Block for {{ _vmu_bin }}"
  when: (not bin_installed.stat.exists) or
        (bin_installed_version.stdout != victoriametrics_cluster_version)
  block:
    - name: "Include download tasks"
      ansible.builtin.include_tasks: download.yml
    - name: "Copy bin to install dir"
      ansible.builtin.copy:
        src: "{{ _victoriametrics_tmp_folder }}/vm{{ _vmu_bin }}-prod"
        dest: "{{ _vmu_full_bin_path }}"
        mode: "0755"
        remote_src: true
