---
### this task file need to be call with the binary whanted to install in the variable _vmu_bin
### the variable _vmu_bin is can be insert, storage or select
- name: "Set bin path fact for vm{{ _vmu_bin }}"
  ansible.builtin.set_fact:
    _vmu_full_bin_path: "{{ _victoriametrics_binary_install_dir }}/vm{{ _vmu_bin }}-prod"

- name: "Check presnece of vm{{ _vmu_bin }}"
  ansible.builtin.stat:
    path: "{{ _vmu_full_bin_path }}"
  register: _bin_installed

- name: "Get installed version of vm{{ _vmu_bin }}"
  ansible.builtin.shell: "{{ _vmu_full_bin_path }} --version | grep -oP 'v\\d+\\.\\d+\\.\\d+'"
  register: _bin_installed_version
  changed_when: false
  failed_when: false
  ignore_errors: true
  when: _bin_installed.stat.exists

- name: "Set facs user & group for {{ _vmu_bin }}"
  ansible.builtin.set_fact:
    _vmu_system_user: "{{ vars['victoriametrics_' + _vmu_bin + '_system_user'] }}"
    _vmu_system_group: "{{ vars['victoriametrics_' + _vmu_bin + '_system_group'] }}"

- name: "Create group for {{ _vmu_bin }}"
  ansible.builtin.group:
    name: "{{ vars['victoriametrics_' + _vmu_bin + '_system_group'] }}"
    state: "present"

- name: "Create user for vm{{ _vmu_bin }}"
  ansible.builtin.user:
    name: "{{ _vmu_system_user }}"
    group: "{{ _vmu_system_group }}"
    state: "present"
    system: true

- name: "Create data dir for vmstorage"
  ansible.builtin.file:
    path: "{{ victoriametrics_storage_path }}"
    state: "directory"
    owner: "{{ victoriametrics_storage_system_user }}"
    group: "{{ victoriametrics_storage_system_group }}"
    mode: "0755"
  when: _vmu_bin == "storage"

- name: "Install Binary Block for vm{{ _vmu_bin }}"
  when: (not _bin_installed.stat.exists) or
        (_bin_installed_version.stdout != victoriametrics_cluster_version)
  block:
    - name: "Include download tasks"
      ansible.builtin.include_tasks: download.yml
      when: not _victoriametrics_cluster_extract is defined or _victoriametrics_cluster_extract is not succeeded

    - name: "Copy bin to install dir"
      ansible.builtin.copy:
        src: "{{ _victoriametrics_tmp_folder }}/vm{{ _vmu_bin }}-prod"
        dest: "{{ _vmu_full_bin_path }}"
        owner: "{{ _vmu_system_user }}"
        group: "{{ _vmu_system_group }}"
        mode: "0755"
        remote_src: true
