---
- name: "Include preflight tasks"
  ansible.builtin.include_tasks: preflight.yml
  tags:
    - always

- name: "Include install tasks for each service enabled"
  ansible.builtin.include_tasks: install_bin.yml
  loop: "{{ _victoriametrics_cluster_service_enabled }}"
  loop_control:
    loop_var: _vmu_bin
  vars:
    _vmu_bin: "{{ item }}"
  tags:
    - install
    - update

- name: "Create config dir"
  ansible.builtin.file:
    path: "{{ _victoriametrics_config_dir }}"
    state: "directory"
    mode: "0755"
  tags:
    - config

- name: "Include config tasks"
  ansible.builtin.include_tasks: config_bin.yml
  loop: "{{ _victoriametrics_cluster_service_enabled }}"
  loop_control:
    loop_var: _vmu_bin
  vars:
    _vmu_bin: "{{ item }}"
  tags:
    - config
