---
# handlers file for msterhuj.victoriametrics_cluster
- name: "Reload systemd vminsert"
  ansible.builtin.systemd:
    daemon_reload: true
  notify: "Restart vminsert"

- name: "Reload systemd vmstorage"
  ansible.builtin.systemd:
    daemon_reload: true
  notify: "Restart vmstorage"

- name: "Reload systemd vmselect"
  ansible.builtin.systemd:
    daemon_reload: true
  notify: "Restart vmselect"

- name: "Restart vminsert"
  ansible.builtin.systemd:
    name: "vminsert"
    state: "restarted"
    enabled: true

- name: "Restart vmstorage"
  ansible.builtin.systemd:
    name: "vmstorage"
    state: "restarted"
    enabled: true

- name: "Restart vmselect"
  ansible.builtin.systemd:
    name: "vmselect"
    state: "restarted"
    enabled: true
